name: Build lab02 artifacts

on:
  push:
    paths:
      - ".github/workflows/build-lab02-temp.yml"
      - "lab02/report/report.md"
      - "lab02/report/image/**"
      - "lab02/presentation/presentation.md"
      - "lab02/presentation/image/**"

permissions:
  contents: write

jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-latex-extra texlive-fonts-recommended texlive-lang-cyrillic fonts-paratype

      - name: Build report
        working-directory: lab02/report
        run: |
          pandoc report.md -o report.pdf --pdf-engine=xelatex
          pandoc report.md -o report.docx

      - name: Build presentation
        working-directory: lab02/presentation
        run: |
          pandoc -t beamer presentation.md -V theme:metropolis -o presentation.pdf --pdf-engine=xelatex
          pandoc -s -t revealjs --slide-level=2 --embed-resources -V revealjs-url=https://unpkg.com/reveal.js@4.6.1 presentation.md -o presentation.html

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add lab02/report/report.pdf lab02/report/report.docx
          git add lab02/presentation/presentation.pdf lab02/presentation/presentation.html
          git commit -m "build: compile lab 2 report and presentation" || exit 0
          git push
